version: '3.8'

services:
  frontend:
    build:
      context: ./house-web
      dockerfile: Dockerfile
    ports:
      - "4299:80"
    networks:
      - app-network

  backend:
    build:
      context: ./house
      dockerfile: Dockerfile
    ports:
      - "8099:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: stage
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: house_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
